add_requires("nlohmann_json")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "."})
target("problog")
    set_kind("binary")
    add_headerfiles("./include/*.hpp")
    add_files("*.cpp")
    add_packages("nlohmann_json")
    set_languages("c++17")
    set_optimize("fastest")
    add_cxxflags("-O3")