add_requires("nlohmann_json")
add_requires("cvc5")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})
target("praline")
    set_kind("binary")
    add_headerfiles("./include/*.hpp")
    add_files("*.cpp")
    add_packages("nlohmann_json")
    add_packages("cvc5")
    set_languages("c++20")
    set_optimize("fastest")
    add_cxxflags("-O3")
    add_links("cvc5")
    add_links("gurobi110")
    add_links("gurobi_c++")
